<a href="https://colab.research.google.com/github/EnVyxS/DIVA_Digital-Intelligence-Virtual-Agent/blob/main/Digital_Intelligence_Virtual_Agent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
# --- Kerangka DIVA v0.0.1 ---
# Sebuah agen interaktif sederhana berbasis teks

import datetime

print("DIVA v0.0.1 Online. Siap menerima perintah. Ketik 'exit' untuk mematikan.")
print("---------------------------------------------------------------------")

# Loop utama agar DIVA selalu "mendengarkan"
while True:
    # Meminta input dari user dan mengubahnya menjadi huruf kecil agar tidak sensitif case
    perintah_user = input("Anda: ")

    # Memeriksa apakah user ingin keluar
    if perintah_user.lower() == "exit":
        print("DIVA: Mematikan sistem. Sampai jumpa, Tuan.")
        break # Keluar dari loop

    # Menambahkan perintah pertama kita
    elif perintah_user.lower() == "siapa kamu?":
        print("DIVA: Saya adalah DIVA, Digital Intelligence Virtual Agent versi 0.0.1. Saya diciptakan untuk melayani Anda.")

    # Menambahkan perintah kedua
    elif perintah_user.lower() == "halo diva":
        print("DIVA: Halo, Tuan. Ada yang bisa saya bantu?")
    # Menanyakan jam berapa
    elif perintah_user.lower() == "jam berapa sekarang?":
        waktu_sekarang = datetime.datetime.now().strftime("%H:%M")
        print(f"DIVA: Sekarang adalah {waktu_sekarang}.")
    # Menanyakan hari apa ini
    elif perintah_user.lower() == "hari apakah sekarang?":
        hari_ini = datetime.datetime.now().strftime("%A")
        print(f"DIVA: Hari ini adalah {hari_ini}.")
    # Menanyakan jam dan hari ini
    elif perintah_user.lower() == "hari apa ini, dan jam berapa?":
        waktu_sekarang = datetime.datetime.now().strftime("%H:%M")
        hari_ini = datetime.datetime.now().strftime("%A")
    # Menanyakan jam berapa di indonesia
    elif perintah_user.lower() == "jam berapa di indonesia?":
        waktu_sekarang = datetime.datetime.now(datetime.timezone(datetime.timedelta(hours=7))).strftime("%H:%M")
        print(f"DIVA: Sekarang adalah {waktu_sekarang} WIB.")
    # Respon default jika perintah tidak dikenali
    else:
        print("DIVA: Maaf, saya belum mengerti perintah tersebut.")

DIVA v0.0.1 Online. Siap menerima perintah. Ketik 'exit' untuk mematikan.
---------------------------------------------------------------------
Anda: exit
DIVA: Mematikan sistem. Sampai jumpa, Tuan.


In [15]:
# --- Kerangka DIVA v0.0.3 ---
# Menambahkan Ingatan Jangka Pendek (Short-Term Memory)

import datetime
from zoneinfo import ZoneInfo

# --- BAGIAN INGATAN DIVA ---
# Kita definisikan variabel ingatan SEBELUM loop dimulai.
# Awalnya kita isi 'None' yang berarti "tidak tahu" atau "kosong".
nama_user = None
asal_kota = None
# ---------------------------

print("DIVA v0.0.3 Online. Saya sekarang memiliki ingatan. Silakan perkenalkan diri Anda.")
print("---------------------------------------------------------------------------------")

while True:
    perintah_user = input("Anda: ")

    if perintah_user.lower() == "exit":
        print("DIVA: Mematikan sistem. Sampai jumpa.")
        break

    # KONDISI BARU: Mengenali perkenalan nama
    # Kita menggunakan "in" agar lebih fleksibel
    elif "nama saya adalah" in perintah_user.lower():
        # .split() akan memecah kalimat menjadi list kata-kata
        # Contoh: "nama saya adalah budi" -> ['nama', 'saya', 'adalah', 'budi']
        # Kita ambil elemen terakhir [-1] yaitu namanya.
        nama_baru = perintah_user.split()[-1]

        # Simpan nama yang didapat ke dalam variabel ingatan
        nama_user = nama_baru.capitalize() # .capitalize() untuk membuat huruf depannya besar

        print(f"DIVA: Baik, Tuan {nama_user}. Nama Anda sudah saya simpan.")

    # KONDISI BARU: Menjawab pertanyaan tentang nama user
    elif "siapa nama saya" in perintah_user.lower():
        if nama_user: # Jika variabel nama_user TIDAK None (sudah diisi)
            print(f"DIVA: Nama Anda adalah Tuan {nama_user}.")
        else: # Jika variabel nama_user masih None
            print("DIVA: Maaf, Tuan. Anda belum memberitahu saya nama Anda.")

    elif "saya berasal dari kota" in perintah_user.lower():
        kota_baru = perintah_user.split()[-1]
        asal_kota = kota_baru.capitalize()
        print(f"DIVA: Baik, Tuan. Kota Anda adalah {asal_kota}.")
    elif "darimana asal kota saya?" in perintah_user.lower():
        if asal_kota:
            print(f"DIVA: Anda berasal dari Kota {asal_kota}.")
        else:
            print("DIVA: Maaf, Anda belum memberitahu saya asal kota Anda.")




    # MODIFIKASI: Menggunakan nama dalam sapaan jika sudah kenal
    elif "halo" in perintah_user.lower():
        if nama_user:
            print(f"DIVA: Halo, Tuan {nama_user}. Senang bertemu Anda lagi.")
        else:
            print("DIVA: Halo, Tuan. Anda bisa memberitahu saya nama Anda dengan mengatakan 'nama saya adalah ...'")

    # Perintah lain dari versi sebelumnya
    elif "jam" in perintah_user.lower() or "waktu" in perintah_user.lower():
        zona_waktu_jakarta = ZoneInfo("Asia/Jakarta")
        waktu_sekarang_jakarta = datetime.datetime.now(datetime.timezone.utc).astimezone(zona_waktu_jakarta)
        print("DIVA: Tentu. Waktu saat ini adalah:", waktu_sekarang_jakarta.strftime("%H:%M:%S"))

    elif "tanggal" in perintah_user.lower():
        zona_waktu_jakarta = ZoneInfo("Asia/Jakarta")
        tanggal_sekarang_jakarta = datetime.datetime.now(datetime.timezone.utc).astimezone(zona_waktu_jakarta)
        print("DIVA: Hari ini adalah:", tanggal_sekarang_jakarta.strftime("%A, %d %B %Y"))

    else:
        print("DIVA: Maaf, saya belum mengerti perintah tersebut.")

DIVA v0.0.3 Online. Saya sekarang memiliki ingatan. Silakan perkenalkan diri Anda.
---------------------------------------------------------------------------------
Anda: exit
DIVA: Mematikan sistem. Sampai jumpa.


In [19]:
# --- Kerangka DIVA v0.0.4 ---
# Menambahkan Ingatan Jangka Panjang dengan JSON

import datetime
from zoneinfo import ZoneInfo
import json
import os

# --- BAGIAN INGATAN DIVA ---
# Kita gunakan dictionary untuk menyimpan semua ingatan
ingatan = {
    "nama_user": None,
    "asal_user": None
}

NAMA_FILE_INGATAN = "ingatan_diva.json"
# ---------------------------

# FUNGSI UNTUK MENGELOLA INGATAN
def simpan_ingatan():
    """Menyimpan dictionary 'ingatan' ke dalam file JSON."""
    with open(NAMA_FILE_INGATAN, "w") as f:
        json.dump(ingatan, f, indent=4)
    print("DEBUG: Ingatan telah disimpan.")

def muat_ingatan():
    """Memuat dictionary 'ingatan' dari file JSON jika ada."""
    global ingatan
    if os.path.exists(NAMA_FILE_INGATAN):
        with open(NAMA_FILE_INGATAN, "r") as f:
            ingatan = json.load(f)
        print("DEBUG: Ingatan telah dimuat dari file.")
    else:
        print("DEBUG: File ingatan tidak ditemukan, memulai dengan ingatan baru.")

# --- SIKLUS HIDUP DIVA ---
muat_ingatan() # Muat ingatan saat program pertama kali dimulai

print("DIVA v0.0.4 Online. Ingatan jangka panjang aktif.")
print("--------------------------------------------------")

while True:
    perintah_user = input("Anda: ")

    if perintah_user.lower() == "exit":
        print("DIVA: Mematikan sistem. Sampai jumpa.")
        break

    elif "nama saya adalah" in perintah_user.lower():
        nama_baru = perintah_user.split()[-1]
        ingatan['nama_user'] = nama_baru.capitalize()
        print(f"DIVA: Baik, Tuan {ingatan['nama_user']}. Nama Anda sudah saya simpan.")
        simpan_ingatan() # Simpan perubahan ingatan

    elif "saya dari" in perintah_user.lower():
        kota_baru = perintah_user.split()[-1]
        ingatan['asal_user'] = kota_baru.capitalize()
        print(f"DIVA: Oke, saya akan ingat bahwa Anda berasal dari {ingatan['asal_user']}.")
        simpan_ingatan() # Simpan perubahan ingatan

    elif "siapa nama saya" in perintah_user.lower():
        if ingatan['nama_user']:
            print(f"DIVA: Nama Anda adalah Tuan {ingatan['nama_user']}.")
        else:
            print("DIVA: Maaf, Tuan. Anda belum memberitahu saya nama Anda.")

    elif "dari mana saya" in perintah_user.lower():
        if ingatan['asal_user']:
            print(f"DIVA: Anda berasal dari {ingatan['asal_user']}, Tuan.")
        else:
            print("DIVA: Maaf, Tuan. Anda belum memberitahu saya kota asal Anda.")

    # Perintah lain dari versi sebelumnya
    elif "halo" in perintah_user.lower():
        if ingatan['nama_user']:
            print(f"DIVA: Halo, Tuan {ingatan['nama_user']}. Senang bertemu Anda lagi.")
        else:
            print("DIVA: Halo, Tuan. Anda bisa memperkenalkan diri.")

    elif "jam" in perintah_user.lower() or "waktu" in perintah_user.lower():
        zona_waktu_jakarta = ZoneInfo("Asia/Jakarta")
        waktu_sekarang_jakarta = datetime.datetime.now(datetime.timezone.utc).astimezone(zona_waktu_jakarta)
        print("DIVA: Tentu. Waktu saat ini adalah:", waktu_sekarang_jakarta.strftime("%H:%M:%S"))

    elif "tanggal" in perintah_user.lower():
        zona_waktu_jakarta = ZoneInfo("Asia/Jakarta")
        tanggal_sekarang_jakarta = datetime.datetime.now(datetime.timezone.utc).astimezone(zona_waktu_jakarta)
        print("DIVA: Hari ini adalah:", tanggal_sekarang_jakarta.strftime("%A, %d %B %Y"))

    else:
        print("DIVA: Maaf, saya belum mengerti perintah tersebut.")

DEBUG: Ingatan telah dimuat dari file.
DIVA v0.0.4 Online. Ingatan jangka panjang aktif.
--------------------------------------------------
Anda: halo
DIVA: Halo, Tuan Envyx. Senang bertemu Anda lagi.
Anda: exit
DIVA: Mematikan sistem. Sampai jumpa.


In [22]:
# --- Kerangka DIVA v0.0.5 ---
# Refactoring dengan Fungsi dan Command Mapping

import datetime
from zoneinfo import ZoneInfo
import json
import os

# --- PENGELOLA INGATAN ---
NAMA_FILE_INGATAN = "ingatan_diva.json"
ingatan = {"nama_user": None, "asal_user": None}

def simpan_ingatan():
    with open(NAMA_FILE_INGATAN, 'w') as f:
        json.dump(ingatan, f, indent=4)

def muat_ingatan():
    global ingatan
    if os.path.exists(NAMA_FILE_INGATAN):
        with open(NAMA_FILE_INGATAN, 'r') as f:
            ingatan = json.load(f)
        print("[DEBUG: Ingatan telah dimuat.]")

# --- KUMPULAN KEMAMPUAN (FUNGSI) DIVA ---
def sapa_user(perintah):
    if ingatan['nama_user']:
        print(f"DIVA: Halo, Tuan {ingatan['nama_user']}. Senang bertemu Anda lagi.")
    else:
        print("DIVA: Halo, Tuan. Anda bisa memperkenalkan diri.")

def ingat_nama(perintah):
    nama_baru = perintah.split()[-1]
    ingatan['nama_user'] = nama_baru.capitalize()
    print(f"DIVA: Baik, Tuan {ingatan['nama_user']}. Nama Anda sudah saya simpan.")
    simpan_ingatan()

def jawab_nama(perintah):
    if ingatan['nama_user']:
        print(f"DIVA: Nama Anda adalah Tuan {ingatan['nama_user']}.")
    else:
        print("DIVA: Maaf, Tuan. Anda belum memberitahu saya nama Anda.")
def ingat_asal_kota(perintah):
    kota_baru = perintah.split()[-1]
    ingatan['asal_user'] = kota_baru.capitalize()
    print(f"DIVA: Oke, saya akan ingat bahwa Anda berasal dari {ingatan['asal_user']}.")
    simpan_ingatan()

def jawab_asal_kota(perintah):
  if ingatan['asal_user']:
    print(f"DIVA: Anda berasal dari {ingatan['asal_user']}, Tuan.")
  else:
    print("DIVA: Maaf, Tuan. Anda belum memberitahu saya kota asal Anda.")

def beritahu_waktu(perintah):
    zona_waktu_jakarta = ZoneInfo("Asia/Jakarta")
    waktu_sekarang = datetime.datetime.now(datetime.timezone.utc).astimezone(zona_waktu_jakarta)
    print(f"DIVA: Tentu. Waktu saat ini adalah: {waktu_sekarang.strftime('%H:%M:%S')}")

def beritahu_tanggal(perintah):
    zona_waktu_jakarta = ZoneInfo("Asia/Jakarta")
    tanggal_sekarang = datetime.datetime.now(datetime.timezone.utc).astimezone(zona_waktu_jakarta)
    print(f"DIVA: Hari ini adalah: {tanggal_sekarang.strftime('%A, %d %B %Y')}")

# --- PUSAT SARAF / COMMAND MAPPING ---
# Kamus yang memetakan kata kunci ke fungsi yang sesuai.
kamus_perintah = {
    "halo": sapa_user,
    "siapa nama saya": jawab_nama,
    "dari mana saya": jawab_asal_kota,
    "saya berasal dari kota": ingat_asal_kota,
    "nama saya adalah": ingat_nama,
    "jam": beritahu_waktu,
    "waktu": beritahu_waktu,
    "tanggal": beritahu_tanggal,
}

# --- SIKLUS HIDUP UTAMA DIVA ---
muat_ingatan()
print("DIVA v0.0.5 Online. Struktur otak telah dioptimalkan.")
print("-----------------------------------------------------")

while True:
    perintah_user = input("Anda: ").lower()
    perintah_dijalankan = False

    if perintah_user == "exit":
        print("DIVA: Mematikan sistem. Sampai jumpa.")
        break

    # Loop utama sekarang hanya mencari di kamus dan memanggil fungsi.
    for kata_kunci, fungsi in kamus_perintah.items():
        if kata_kunci in perintah_user:
            fungsi(perintah_user)
            perintah_dijalankan = True
            break # Hentikan pencarian setelah perintah pertama ditemukan

    if not perintah_dijalankan:
        print("DIVA: Maaf, saya belum mengerti perintah tersebut.")

[DEBUG: Ingatan telah dimuat.]
DIVA v0.0.5 Online. Struktur otak telah dioptimalkan.
-----------------------------------------------------
Anda: dari mana saya
DIVA: Anda berasal dari Semarang, Tuan.
DIVA: Mematikan sistem. Sampai jumpa.


In [23]:
!pip install thefuzz

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 28.8 MB/s eta 0:00:00


In [28]:
# --- Kerangka DIVA v0.0.6 ---
# Menggunakan Fuzzy Matching untuk toleransi kesalahan

# Pastikan Anda sudah menjalankan !pip install thefuzz di sel terpisah
import datetime
from zoneinfo import ZoneInfo
import json
import os
from thefuzz import fuzz # Impor library fuzzy matching

# --- PENGELOLA INGATAN & FUNGSI KEMAMPUAN ---
# (Bagian ini sama persis dengan v0.0.5, tidak perlu diubah)
NAMA_FILE_INGATAN = "ingatan_diva.json"
ingatan = {"nama_user": None, "asal_user": None}
def simpan_ingatan():
    with open(NAMA_FILE_INGATAN, 'w') as f: json.dump(ingatan, f, indent=4)
def muat_ingatan():
    global ingatan
    if os.path.exists(NAMA_FILE_INGATAN):
        with open(NAMA_FILE_INGATAN, 'r') as f: ingatan = json.load(f)
        print("[DEBUG: Ingatan telah dimuat.]")
def sapa_user(perintah):
    if ingatan['nama_user']: print(f"DIVA: Halo, Tuan {ingatan['nama_user']}.")
    else: print("DIVA: Halo, Tuan.")
def ingat_nama(perintah):
    nama_baru = perintah.split()[-1]
    ingatan['nama_user'] = nama_baru.capitalize()
    print(f"DIVA: Baik, Tuan {ingatan['nama_user']}. Nama Anda sudah saya simpan.")
    simpan_ingatan()
def jawab_nama(perintah):
    if ingatan['nama_user']: print(f"DIVA: Nama Anda adalah Tuan {ingatan['nama_user']}.")
    else: print("DIVA: Maaf, Tuan. Anda belum memberitahu saya nama Anda.")
def beritahu_waktu(perintah):
    zona_waktu_jakarta = ZoneInfo("Asia/Jakarta")
    waktu_sekarang = datetime.datetime.now(datetime.timezone.utc).astimezone(zona_waktu_jakarta)
    print(f"DIVA: Tentu. Waktu saat ini adalah: {waktu_sekarang.strftime('%H:%M:%S')}")
def beritahu_tanggal(perintah):
    zona_waktu_jakarta = ZoneInfo("Asia/Jakarta")
    tanggal_sekarang = datetime.datetime.now(datetime.timezone.utc).astimezone(zona_waktu_jakarta)
    print(f"DIVA: Hari ini adalah: {tanggal_sekarang.strftime('%A, %d %B %Y')}")
# ----------------------------------------------------------------

# --- PUSAT SARAF / COMMAND MAPPING ---
kamus_perintah = {
    "halo": sapa_user, "siapa nama saya": jawab_nama, "nama saya adalah": ingat_nama,
    "jam": beritahu_waktu, "waktu": beritahu_waktu, "tanggal": beritahu_tanggal,
}

# --- SIKLUS HIDUP UTAMA DIVA (VERSI BARU DENGAN FUZZY LOGIC) ---
muat_ingatan()
print("DIVA v0.0.6 Online. Logika pemahaman telah di-upgrade.")
print("---------------------------------------------------------")

THRESHOLD = 60 # Tentukan ambang batas kepercayaan (0-100)

while True:
    perintah_user = input("Anda: ").lower()

    if perintah_user == "exit":
        print("DIVA: Mematikan sistem. Sampai jumpa.")
        break

    # 1. Cari perintah dengan skor kemiripan tertinggi
    skor_tertinggi = 0
    fungsi_terpilih = None

    for kata_kunci, fungsi in kamus_perintah.items():
        # fuzz.ratio menghitung kemiripan standar
        skor_saat_ini = fuzz.ratio(perintah_user, kata_kunci)
        if skor_saat_ini > skor_tertinggi:
            skor_tertinggi = skor_saat_ini
            fungsi_terpilih = fungsi

    # 2. Periksa apakah skor tertinggi melewati ambang batas
    if skor_tertinggi > THRESHOLD:
        fungsi_terpilih(perintah_user)
    else:
        print(f"DIVA: Maaf, saya kurang yakin maksud Anda (Skor terbaik: {skor_tertinggi}). Bisa perjelas?")

[DEBUG: Ingatan telah dimuat.]
DIVA v0.0.6 Online. Logika pemahaman telah di-upgrade.
---------------------------------------------------------
Anda: sp nm sy
DIVA: Nama Anda adalah Tuan Diva.
Anda: nm sy adlh EnVyx
DIVA: Baik, Tuan Envyx. Nama Anda sudah saya simpan.
Anda: exit
DIVA: Mematikan sistem. Sampai jumpa.


In [34]:
# Impor library yang dibutuhkan
from sklearn.feature_extraction.text import CountVectorizer

# 1. Siapkan data latih kita (disebut juga corpus)
corpus = [
    'halo diva',
    'halo tuan',
    'selamat pagi diva',
    'jam berapa sekarang',
    'sekarang pukul berapa',
    'apa yang akan dimakan?',
    'darimana asalmu?',
    'kita bisa',
    'coba buka youtube'
]

# 2. Buat objek CountVectorizer
vectorizer = CountVectorizer()

# 3. Ubah teks menjadi vektor
X = vectorizer.fit_transform(corpus)

# 4. Mari kita lihat hasilnya
print("Kosakata (Vocabulary):")
print(vectorizer.get_feature_names_out())

print("\nHasil Vectorization (Matriks):")
print(X.toarray())

Kosakata (Vocabulary):
['akan' 'apa' 'asalmu' 'berapa' 'bisa' 'buka' 'coba' 'darimana' 'dimakan'
 'diva' 'halo' 'jam' 'kita' 'pagi' 'pukul' 'sekarang' 'selamat' 'tuan'
 'yang' 'youtube']

Hasil Vectorization (Matriks):
[[0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0]
 [1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1]]


In [45]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import make_pipeline

# --- DATA LATIH (CORPUS & LABELS) ---
# Corpus berisi kalimat, labels berisi "niat" atau intent dari setiap kalimat.
# Urutannya harus sesuai.
corpus = [
    'halo', 'hai diva', 'selamat pagi',                     # Niat: menyapa
    'jam berapa', 'sekarang pukul berapa', 'waktu',        # Niat: bertanya_waktu
    'tanggal berapa hari ini', 'info tanggal',             # Niat: bertanya_tanggal
    'nama saya budi', 'nama ku adalah budi'                # Niat: memberitahu_nama
]
labels = [
    'menyapa', 'menyapa', 'menyapa',
    'bertanya_waktu', 'bertanya_waktu', 'bertanya_waktu',
    'bertanya_tanggal', 'bertanya_tanggal',
    'memberitahu_nama', 'memberitahu_nama'
]

# --- MEMBANGUN MODEL ---
# Kita gunakan 'pipeline' untuk menggabungkan dua langkah: vectorization dan klasifikasi.
# 1. CountVectorizer() akan mengubah teks menjadi vektor.
# 2. KNeighborsClassifier(n_neighbors=1) akan melakukan klasifikasi KNN.
# n_neighbors=1 berarti kita hanya melihat 1 tetangga terdekat.
model = make_pipeline(CountVectorizer(), KNeighborsClassifier(n_neighbors=3))

# --- MELATIH MODEL ---
# Proses "belajar" di mana model menghafal posisi semua data latih.
model.fit(corpus, labels)

# --- PENGUJIAN MODEL ---
# Mari kita uji dengan kalimat yang belum pernah dilihat model sebelumnya.
kalimat_baru_1 = "pagi"
kalimat_baru_2 = "sekarang jam berapa ya?"
kalimat_baru_3 = "namaku budi"

# Model akan memprediksi 'niat' dari kalimat baru.
prediksi_1 = model.predict([kalimat_baru_1])
prediksi_2 = model.predict([kalimat_baru_2])
prediksi_3 = model.predict([kalimat_baru_3])

print(f"Kalimat: '{kalimat_baru_1}' -> Prediksi Intent: {prediksi_1[0]}")
print(f"Kalimat: '{kalimat_baru_2}' -> Prediksi Intent: {prediksi_2[0]}")
print(f"Kalimat: '{kalimat_baru_3}' -> Prediksi Intent: {prediksi_3[0]}")

Kalimat: 'pagi' -> Prediksi Intent: menyapa
Kalimat: 'sekarang jam berapa ya?' -> Prediksi Intent: bertanya_waktu
Kalimat: 'namaku budi' -> Prediksi Intent: bertanya_waktu


In [50]:
# CONTOH DATASET LENGKAP UNTUK DIVA v0.2

# List berisi kalimat-kalimat contoh dari pengguna
texts = [
    # --- Intent: menyapa (10 contoh) ---
    'halo', 'hai diva', 'selamat pagi', 'pagi', 'permisi',
    'bro', 'hi', 'apa kabar', 'selamat datang', 'sampurasun',

    # --- Intent: bertanya_waktu (10 contoh) ---
    'jam berapa sekarang', 'pukul berapa', 'info waktu dong', 'sekarang jam brp?', 'jamberapa?',
    'kasih tau jam', 'waktunya apa', 'jam berapa ya sekarang', 'tolong info waktu', 'waktu saat ini',

    # --- Intent: bertanya_tanggal (10 contoh) ---
    'tanggal berapa hari ini', 'sekarang tanggal berapa', 'info tanggal dong', 'hari ini tgl brp?', 'tanggalnya berapa',
    'kasih tau tanggal hari ini', 'tanggal', 'kalender hari ini', 'info kalender', 'tanggal brp skrg',

    # --- Intent: memberitahu_nama (10 contoh) ---
    'nama saya budi', 'namaku adalah budi', 'panggil saja saya budi', 'saya budi', 'kenalin namaku budi',
    'nama lengkapku budi setiawan', 'ini budi', 'bisa panggil aku budi', 'aku budi', 'namaku budi ya',

    # --- Intent: kemampuan_diva (10 contoh) ---
    'kamu bisa apa saja?', 'apa saja kemampuanmu', 'fitur kamu apa', 'apa yang bisa kamu lakukan', 'jelaskan kemampuanmu',
    'bisa bantu apa', 'skill kamu apa aja', 'kamu bisa ngapain', 'apa gunanya kamu', 'tunjukkan fiturmu',

    # --- Intent: perpisahan (10 contoh) ---
    'sampai jumpa', 'exit', 'keluar', 'bye', 'selamat tinggal',
    'saya pergi dulu', 'matikan sistem', 'dah', 'selesai', 'cukup'
]

# List berisi label/intent yang sesuai dengan setiap kalimat di atas
labels = [
    # --- Intent: menyapa (10 label) ---
    'menyapa', 'menyapa', 'menyapa', 'menyapa', 'menyapa',
    'menyapa', 'menyapa', 'menyapa', 'menyapa', 'menyapa',

    # --- Intent: bertanya_waktu (10 label) ---
    'bertanya_waktu', 'bertanya_waktu', 'bertanya_waktu', 'bertanya_waktu', 'bertanya_waktu',
    'bertanya_waktu', 'bertanya_waktu', 'bertanya_waktu', 'bertanya_waktu', 'bertanya_waktu',

    # --- Intent: bertanya_tanggal (10 label) ---
    'bertanya_tanggal', 'bertanya_tanggal', 'bertanya_tanggal', 'bertanya_tanggal', 'bertanya_tanggal',
    'bertanya_tanggal', 'bertanya_tanggal', 'bertanya_tanggal', 'bertanya_tanggal', 'bertanya_tanggal',

    # --- Intent: memberitahu_nama (10 label) ---
    'memberitahu_nama', 'memberitahu_nama', 'memberitahu_nama', 'memberitahu_nama', 'memberitahu_nama',
    'memberitahu_nama', 'memberitahu_nama', 'memberitahu_nama', 'memberitahu_nama', 'memberitahu_nama',

    # --- Intent: kemampuan_diva (10 label) ---
    'kemampuan_diva', 'kemampuan_diva', 'kemampuan_diva', 'kemampuan_diva', 'kemampuan_diva',
    'kemampuan_diva', 'kemampuan_diva', 'kemampuan_diva', 'kemampuan_diva', 'kemampuan_diva',

    # --- Intent: perpisahan (10 label) ---
    'perpisahan', 'perpisahan', 'perpisahan', 'perpisahan', 'perpisahan',
    'perpisahan', 'perpisahan', 'perpisahan', 'perpisahan', 'perpisahan'
]

# Cek untuk memastikan jumlahnya sama
if len(texts) == len(labels):
    print(f"Dataset siap digunakan! Total data: {len(texts)} kalimat.")
else:
    print(f"ERROR: Jumlah teks ({len(texts)}) tidak sama dengan jumlah label ({len(labels)}).")

Dataset siap digunakan! Total data: 60 kalimat.


In [53]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import make_pipeline

# --- DATA LATIH (CORPUS & LABELS) ---
# Corpus berisi kalimat, labels berisi "niat" atau intent dari setiap kalimat.
# Urutannya harus sesuai.
corpus = [
    # --- Intent: menyapa (10 contoh) ---
    'halo', 'hai diva', 'selamat pagi', 'pagi', 'permisi',
    'bro', 'hi', 'apa kabar', 'selamat datang', 'sampurasun',

    # --- Intent: bertanya_waktu (10 contoh) ---
    'jam berapa sekarang', 'pukul berapa', 'info waktu dong', 'sekarang jam brp?', 'jamberapa?',
    'kasih tau jam', 'waktunya apa', 'jam berapa ya sekarang', 'tolong info waktu', 'waktu saat ini',

    # --- Intent: bertanya_tanggal (10 contoh) ---
    'tanggal berapa hari ini', 'sekarang tanggal berapa', 'info tanggal dong', 'hari ini tgl brp?', 'tanggalnya berapa',
    'kasih tau tanggal hari ini', 'tanggal', 'kalender hari ini', 'info kalender', 'tanggal brp skrg',

    # --- Intent: memberitahu_nama (10 contoh) ---
    'nama saya budi', 'namaku adalah budi', 'panggil saja saya budi', 'saya budi', 'kenalin namaku budi',
    'nama lengkapku budi setiawan', 'ini budi', 'bisa panggil aku budi', 'aku budi', 'namaku budi ya',

    # --- Intent: kemampuan_diva (10 contoh) ---
    'kamu bisa apa saja?', 'apa saja kemampuanmu', 'fitur kamu apa', 'apa yang bisa kamu lakukan', 'jelaskan kemampuanmu',
    'bisa bantu apa', 'skill kamu apa aja', 'kamu bisa ngapain', 'apa gunanya kamu', 'tunjukkan fiturmu',

    # --- Intent: perpisahan (10 contoh) ---
    'sampai jumpa', 'exit', 'keluar', 'bye', 'selamat tinggal',
    'saya pergi dulu', 'matikan sistem', 'dah', 'selesai', 'cukup'
]
labels = [
    # --- Intent: menyapa (10 label) ---
    'menyapa', 'menyapa', 'menyapa', 'menyapa', 'menyapa',
    'menyapa', 'menyapa', 'menyapa', 'menyapa', 'menyapa',

    # --- Intent: bertanya_waktu (10 label) ---
    'bertanya_waktu', 'bertanya_waktu', 'bertanya_waktu', 'bertanya_waktu', 'bertanya_waktu',
    'bertanya_waktu', 'bertanya_waktu', 'bertanya_waktu', 'bertanya_waktu', 'bertanya_waktu',

    # --- Intent: bertanya_tanggal (10 label) ---
    'bertanya_tanggal', 'bertanya_tanggal', 'bertanya_tanggal', 'bertanya_tanggal', 'bertanya_tanggal',
    'bertanya_tanggal', 'bertanya_tanggal', 'bertanya_tanggal', 'bertanya_tanggal', 'bertanya_tanggal',

    # --- Intent: memberitahu_nama (10 label) ---
    'memberitahu_nama', 'memberitahu_nama', 'memberitahu_nama', 'memberitahu_nama', 'memberitahu_nama',
    'memberitahu_nama', 'memberitahu_nama', 'memberitahu_nama', 'memberitahu_nama', 'memberitahu_nama',

    # --- Intent: kemampuan_diva (10 label) ---
    'kemampuan_diva', 'kemampuan_diva', 'kemampuan_diva', 'kemampuan_diva', 'kemampuan_diva',
    'kemampuan_diva', 'kemampuan_diva', 'kemampuan_diva', 'kemampuan_diva', 'kemampuan_diva',

    # --- Intent: perpisahan (10 label) ---
    'perpisahan', 'perpisahan', 'perpisahan', 'perpisahan', 'perpisahan',
    'perpisahan', 'perpisahan', 'perpisahan', 'perpisahan', 'perpisahan'
]

# --- MEMBANGUN MODEL ---
# Kita gunakan 'pipeline' untuk menggabungkan dua langkah: vectorization dan klasifikasi.
# 1. CountVectorizer() akan mengubah teks menjadi vektor.
# 2. KNeighborsClassifier(n_neighbors=1) akan melakukan klasifikasi KNN.
# n_neighbors=1 berarti kita hanya melihat 1 tetangga terdekat.
model = make_pipeline(CountVectorizer(), KNeighborsClassifier(n_neighbors=3))

# --- MELATIH MODEL ---
# Proses "belajar" di mana model menghafal posisi semua data latih.
model.fit(corpus, labels)

# --- PENGUJIAN MODEL ---
# Mari kita uji dengan kalimat yang belum pernah dilihat model sebelumnya.
kalimat_baru_1 = "pagi"
kalimat_baru_2 = "sekarang jam berapa ya?"
kalimat_baru_3 = "namaku budi"

# Model akan memprediksi 'niat' dari kalimat baru.
prediksi_1 = model.predict([kalimat_baru_1])
prediksi_2 = model.predict([kalimat_baru_2])
prediksi_3 = model.predict([kalimat_baru_3])

print(f"Kalimat: '{kalimat_baru_1}' -> Prediksi Intent: {prediksi_1[0]}")
print(f"Kalimat: '{kalimat_baru_2}' -> Prediksi Intent: {prediksi_2[0]}")
print(f"Kalimat: '{kalimat_baru_3}' -> Prediksi Intent: {prediksi_3[0]}")

Kalimat: 'pagi' -> Prediksi Intent: menyapa
Kalimat: 'sekarang jam berapa ya?' -> Prediksi Intent: bertanya_waktu
Kalimat: 'namaku budi' -> Prediksi Intent: memberitahu_nama


In [61]:
from sklearn.feature_extraction.text import TfidfVectorizer # Ganti import
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import make_pipeline

# --- DATASET v0.2 ---
# (Gunakan dataset lengkap dari pertemuan sebelumnya)
texts = [
    # --- Intent: menyapa (10 contoh) ---
    'halo', 'hai diva', 'selamat pagi', 'pagi', 'permisi', 'bro', 'hi', 'apa kabar', 'selamat datang', 'sampurasun',
    # --- Intent: bertanya_waktu (10 contoh) ---
    'jam berapa sekarang', 'pukul berapa', 'info waktu dong', 'sekarang jam brp?', 'jamberapa?', 'kasih tau jam', 'waktunya apa', 'jam berapa ya sekarang', 'tolong info waktu', 'waktu saat ini',
    # --- Intent: bertanya_tanggal (10 contoh) ---
    'tanggal berapa hari ini', 'sekarang tanggal berapa', 'info tanggal dong', 'hari ini tgl brp?', 'tanggalnya berapa', 'kasih tau tanggal hari ini', 'tanggal', 'kalender hari ini', 'info kalender', 'tanggal brp skrg',
    # --- Intent: memberitahu_nama (10 contoh) ---
    'nama saya budi', 'namaku adalah budi', 'panggil saja saya budi', 'saya budi', 'kenalin namaku budi', 'nama lengkapku budi setiawan', 'ini budi', 'bisa panggil aku budi', 'aku budi', 'namaku budi ya',
    # --- Intent: kemampuan_diva (10 contoh) ---
    'kamu bisa apa saja?', 'apa saja kemampuanmu', 'fitur kamu apa', 'apa yang bisa kamu lakukan', 'jelaskan kemampuanmu', 'bisa bantu apa', 'skill kamu apa aja', 'kamu bisa ngapain', 'apa gunanya kamu', 'tunjukkan fiturmu',
    # --- Intent: perpisahan (10 contoh) ---
    'sampai jumpa', 'exit', 'keluar', 'bye', 'selamat tinggal', 'saya pergi dulu', 'matikan sistem', 'dah', 'selesai', 'cukup'
]
labels = [
    'menyapa', 'menyapa', 'menyapa', 'menyapa', 'menyapa', 'menyapa', 'menyapa', 'menyapa', 'menyapa', 'menyapa',
    'bertanya_waktu', 'bertanya_waktu', 'bertanya_waktu', 'bertanya_waktu', 'bertanya_waktu', 'bertanya_waktu', 'bertanya_waktu', 'bertanya_waktu', 'bertanya_waktu', 'bertanya_waktu',
    'bertanya_tanggal', 'bertanya_tanggal', 'bertanya_tanggal', 'bertanya_tanggal', 'bertanya_tanggal', 'bertanya_tanggal', 'bertanya_tanggal', 'bertanya_tanggal', 'bertanya_tanggal', 'bertanya_tanggal',
    'memberitahu_nama', 'memberitahu_nama', 'memberitahu_nama', 'memberitahu_nama', 'memberitahu_nama', 'memberitahu_nama', 'memberitahu_nama', 'memberitahu_nama', 'memberitahu_nama', 'memberitahu_nama',
    'kemampuan_diva', 'kemampuan_diva', 'kemampuan_diva', 'kemampuan_diva', 'kemampuan_diva', 'kemampuan_diva', 'kemampuan_diva', 'kemampuan_diva', 'kemampuan_diva', 'kemampuan_diva',
    'perpisahan', 'perpisahan', 'perpisahan', 'perpisahan', 'perpisahan', 'perpisahan', 'perpisahan', 'perpisahan', 'perpisahan', 'perpisahan'
]

# --- MEMBANGUN MODEL DENGAN TF-IDF ---
# Ganti CountVectorizer() dengan TfidfVectorizer()
model_tfidf = make_pipeline(TfidfVectorizer(), KNeighborsClassifier(n_neighbors=3))

# --- MELATIH MODEL ---
model_tfidf.fit(texts, labels)

# --- PENGUJIAN MODEL ---
kalimat_uji = "jelasin dong skillmu apa saja"
prediksi = model_tfidf.predict([kalimat_uji])

print(f"Dataset v0.2 siap digunakan! Total data: {len(texts)} kalimat.")
print("---")
print("Model baru dengan TF-IDF telah dilatih.")
print(f"Kalimat Uji: '{kalimat_uji}' -> Prediksi Intent: {prediksi[0]}")

Dataset v0.2 siap digunakan! Total data: 60 kalimat.
---
Model baru dengan TF-IDF telah dilatih.
Kalimat Uji: 'jelasin dong skillmu apa saja' -> Prediksi Intent: kemampuan_diva


In [65]:
#
# Sel ini hanya perlu dijalankan sekali saja untuk mengunduh model.
# Setelah diunduh, file akan tersimpan di environment Colab Anda.
#
import requests

url = "https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.id.300.bin.gz"
file_name = "cc.id.300.bin.gz"

print("Mengunduh model FastText... Ini mungkin memakan waktu beberapa menit.")
with open(file_name, "wb") as f:
    response = requests.get(url, stream=True)
    total_length = response.headers.get('content-length')

    if total_length is None: # no content length header
        f.write(response.content)
    else:
        dl = 0
        total_length = int(total_length)
        for data in response.iter_content(chunk_size=4096):
            dl += len(data)
            f.write(data)
            done = int(50 * dl / total_length)
            print(f"\r[{'=' * done}{' ' * (50-done)}] {dl * 100 / total_length:.2f}%", end='')
print("\nDownload selesai.")

# Unzip file
import gzip
import shutil

print("Mengekstrak model...")
with gzip.open(file_name, 'rb') as f_in:
    with open('cc.id.300.bin', 'wb') as f_out:
        shutil.copyfileobj(f_in, f_out)
print("Ekstraksi selesai.")

Mengunduh model FastText... Ini mungkin memakan waktu beberapa menit.
[==================================================] 100.00%
Download selesai.
Mengekstrak model...
Ekstraksi selesai.


In [66]:
!pip install fasttext

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.4/73.4 kB 2.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached pybind11-2.13.6-py3-none-any.whl.metadata (9.5 kB)
Using cached pybind11-2.13.6-py3-none-any.whl (243 kB)
  Created wheel for fasttext: filename=fasttext-0.9.3-cp311-cp311-linux_x86_64.whl size=4313507 sha256=33a0f3f7771ead736cb3305079c419b9e72c9abb81bc3cdda6ac1adf32dfa7e9
  Stored in directory: /root/.cache/pip/wheels/65/4f/35/5057db0249224e9ab55a513fa6b79451473ceb7713017823c3
Successfully built fasttext


In [67]:
import fasttext

print("Memuat model FastText ke memori...")
# Muat model. Parameter .bin menunjukkan file binary yang sudah ditraining.
model_ft = fasttext.load_model('cc.id.300.bin')
print("Model berhasil dimuat.")

# --- PENGUJIAN KEMAMPUAN ---
print("\n--- Tes 1: Mencari Sinonim ---")
# Cari 5 kata yang paling mirip dengan kata "jam"
kata_mirip = model_ft.get_nearest_neighbors('jam', k=5)
print("Kata yang mirip dengan 'jam':")
for skor, kata in kata_mirip:
    print(f"- {kata} (Skor: {skor:.4f})")

print("\n--- Tes 2: Analogi Kata ---")
# Ini menunjukkan pemahaman hubungan antar kata.
# Misal: "raja - pria + wanita = ?" -> seharusnya "ratu"
# Di sini kita coba: "jakarta - indonesia + malaysia = ?" -> seharusnya "kuala lumpur"
analogi = model_ft.get_analogies("jakarta", "indonesia", "malaysia")
print("Hasil analogi 'jakarta - indonesia + malaysia':")
for skor, kata in analogi:
    print(f"- {kata} (Skor: {skor:.4f})")

print("\n--- Tes 3: Mendapatkan Vektor Kalimat ---")
# Dapatkan representasi vektor dari sebuah kalimat
vektor_kalimat = model_ft.get_sentence_vector("pukul berapa sekarang ya?")
print(f"Vektor untuk kalimat 'pukul berapa sekarang ya?':")
print(f"Dimensi vektor: {vektor_kalimat.shape}")
print(f"Contoh isi vektor: {vektor_kalimat[:10]}") # Tampilkan 10 angka pertama

Memuat model FastText ke memori...
Model berhasil dimuat.

--- Tes 1: Mencari Sinonim ---
Kata yang mirip dengan 'jam':
- Jam (Skor: 0.7129)
- -jam (Skor: 0.6483)
- jamnya (Skor: 0.6482)
- menit (Skor: 0.6443)
- menit-an (Skor: 0.6439)

--- Tes 2: Analogi Kata ---
Hasil analogi 'jakarta - indonesia + malaysia':
- jakarta. (Skor: 0.5595)
- kejakarta (Skor: 0.5521)
- jakarta- (Skor: 0.5301)
- malaysia. (Skor: 0.5258)
- jakartaHati (Skor: 0.5253)
- dijakarta (Skor: 0.5196)
- malaysai (Skor: 0.5110)
- 1malaysia (Skor: 0.5072)
- johor (Skor: 0.5048)
- jakartaDr (Skor: 0.4992)

--- Tes 3: Mendapatkan Vektor Kalimat ---
Vektor untuk kalimat 'pukul berapa sekarang ya?':
Dimensi vektor: (300,)
Contoh isi vektor: [-0.02508383 -0.02530499  0.01396769  0.05269853 -0.00513565 -0.03760912
  0.01911997  0.0100432  -0.00384782 -0.05812953]


In [69]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

# Diasumsikan model 'model_ft' sudah dimuat dari pertemuan sebelumnya.
# Diasumsikan dataset 'texts' dan 'labels' (v0.2) juga sudah ada.
# -------------------------------------------------------------------

# --- LANGKAH 1: Vectorization Manual dengan FastText ---
print("Membuat vektor untuk setiap kalimat dalam dataset...")
# Kita gunakan list comprehension untuk proses yang ringkas.
# np.array mengubah list vektor menjadi format yang lebih efisien.
X_train = np.array([model_ft.get_sentence_vector(text) for text in texts])
y_train = np.array(labels)

print(f"Vectorization selesai. Bentuk data latih (X_train): {X_train.shape}")


# --- LANGKAH 2: Melatih Model Klasifikasi ---
print("Melatih model KNeighborsClassifier...")
# Kita tidak lagi butuh pipeline karena vectorization sudah dilakukan.
knn_model_ft = KNeighborsClassifier(n_neighbors=1)
knn_model_ft.fit(X_train, y_train)
print("Model baru (knn_model_ft) berhasil dilatih!")


# --- LANGKAH 3: PENGUJIAN MODEL ---
print("\n--- Pengujian Model Baru ---")
# Daftar kalimat uji yang sebelumnya mungkin gagal.
kalimat_uji_list = [
    "pukul berapa?",            # Menggunakan sinonim 'pukul'
    "jelasin dong skill kamu",  # Menggunakan typo 'jelasin' dan 'skill'
    "saya undur diri"           # Menggunakan sinonim untuk 'perpisahan'
]

for kalimat_uji in kalimat_uji_list:
    # Untuk prediksi, kita juga harus mengubah kalimat uji menjadi vektor.
    vektor_uji = model_ft.get_sentence_vector(kalimat_uji)

    # Lakukan prediksi pada vektor tersebut.
    # [vektor_uji] karena model mengharapkan input 2D.
    prediksi = knn_model_ft.predict([vektor_uji])

    print(f"Kalimat: '{kalimat_uji}' -> Prediksi Intent: {prediksi[0]}")

Membuat vektor untuk setiap kalimat dalam dataset...
Vectorization selesai. Bentuk data latih (X_train): (60, 300)
Melatih model KNeighborsClassifier...
Model baru (knn_model_ft) berhasil dilatih!

--- Pengujian Model Baru ---
Kalimat: 'pukul berapa?' -> Prediksi Intent: bertanya_waktu
Kalimat: 'jelasin dong skill kamu' -> Prediksi Intent: kemampuan_diva
Kalimat: 'saya undur diri' -> Prediksi Intent: perpisahan


In [84]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Diasumsikan model 'model_ft' dan dataset 'texts', 'labels' sudah ada.
# -------------------------------------------------------------------

# --- LANGKAH 1: Vectorization (Sama seperti sebelumnya) ---
print("Membuat vektor untuk seluruh dataset...")
X = np.array([model_ft.get_sentence_vector(text) for text in texts])
y = np.array(labels)
print(f"Vectorization selesai. Total data: {len(X)}")


# --- LANGKAH 2: Train-Test Split ---
# Kita bagi data menjadi 80% untuk latih dan 20% untuk uji.
# random_state=42 memastikan pembagiannya selalu sama setiap kali kode dijalankan.
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
print(f"Data dibagi menjadi: {len(X_train)} data latih dan {len(X_test)} data uji.")


# --- LANGKAH 3: Melatih Model HANYA pada Data Latih ---
print("Melatih model KNN hanya pada data latih...")
model_final = KNeighborsClassifier(n_neighbors=3)
model_final.fit(X_train, y_train)
print("Model berhasil dilatih.")


# --- LANGKAH 4: Melakukan Prediksi pada Data Uji ---
print("Melakukan prediksi pada data uji (data yang belum pernah dilihat model)...")
y_pred = model_final.predict(X_test)


# --- LANGKAH 5: Mengukur Akurasi ---
akurasi = accuracy_score(y_test, y_pred)
print("\n--- HASIL EVALUASI MODEL ---")
print(f"Akurasi Model: {akurasi * 100:.2f}%")

# Menampilkan perbandingan hasil prediksi dan label asli untuk analisis
print("\nDetail Prediksi pada Data Uji:")
for i in range(len(X_test)):
    label_asli = y_test[i]
    prediksi_model = y_pred[i]
    status = "BENAR" if label_asli == prediksi_model else "SALAH"
    print(f"- Label Asli: {label_asli:<18} | Prediksi: {prediksi_model:<18} | Status: {status}")

Membuat vektor untuk seluruh dataset...
Vectorization selesai. Total data: 60
Data dibagi menjadi: 48 data latih dan 12 data uji.
Melatih model KNN hanya pada data latih...
Model berhasil dilatih.
Melakukan prediksi pada data uji (data yang belum pernah dilihat model)...

--- HASIL EVALUASI MODEL ---
Akurasi Model: 58.33%

Detail Prediksi pada Data Uji:
- Label Asli: menyapa              | Prediksi: memberitahu_nama   | Status: SALAH
- Label Asli: menyapa              | Prediksi: bertanya_tanggal   | Status: SALAH
- Label Asli: memberitahu_nama     | Prediksi: memberitahu_nama   | Status: BENAR
- Label Asli: kemampuan_diva       | Prediksi: kemampuan_diva     | Status: BENAR
- Label Asli: bertanya_waktu       | Prediksi: bertanya_waktu     | Status: BENAR
- Label Asli: perpisahan           | Prediksi: menyapa            | Status: SALAH
- Label Asli: memberitahu_nama     | Prediksi: memberitahu_nama   | Status: BENAR
- Label Asli: kemampuan_diva       | Prediksi: kemampuan_diva     | St